oz-consolidation-2Team/FE

src/App.jsx
src/pages/SignUpPage/CompanySignPage.jsx
src/pages/SignUpPage/SignUpPage.scss
src/pages/SignUpPage/UserSignUpPage.jsx
src/pages/SignUpPage/index.jsx

- 회원가입 유형 페이지 생성
개인, 기업 가입 버튼 누를 시 페이지로 전환
- 뒤로가는 헤더 만들어서 연결해야함
- 개인, 기업 가입 폼 미 작성

✨ Feat : 회원가입 유형 페이지 생성

---

src/components/BackHeader/BackHeader.scss
src/components/BackHeader/index.jsx
src/pages/SignUpPage/index.jsx

- 뒤로가기 네비게이션 생성
뒤로가기 정상 작동, 로고 이미지 클릭 시 홈페이지 이동
-

✨ Feat : 뒤로가기 네비게이션 생성

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
jsconfig.json
vite.config.js

- CI/ CD 문제 확인 후 내용 적용 테스트 입니다~!
-기능이 정상 동작하나요?
- 팀 규칙에 맞게 커밋 메시지를 작성했나요?
-

✅ Test :  CI/CD 후 CSS 작동 여부 테스트 확인

---

.github/workflows/deploy-dev.yml

-
기능이 정상 동작하나요?
팀 규칙에 맞게 커밋 메시지를 작성했나요?
-

✅[test] CI/CD 파일 구조 수정 중 - TEST11

---

.github/workflows/deploy-dev.yml

✅[test] CI/CD 파일 구조 수정 중 - TEST12

---

src/pages/SignUpPage/CompanySignPage.jsx
src/pages/SignUpPage/CompanySignPage.scss
src/utils/validation.js

- 기업 회원가입 페이지 생성
- 전환페이지로 구성
- 코드 정리 필요, 개인회원가입페이지랑 공통 컴포넌트 묶을 예정

✨ Feat : 기업 회원가입 페이지 생성

---

src/App.jsx
src/pages/RecruitmentInfo/index.jsx

라우터 경로 수정 (채용정보 뒤로가기버튼 삭제)
-채용정보페이지,검색결과 페이지,채용상세정보 페이지 라우터 경로 수정
- 채용정보 페이지 뒤로가기 버튼 삭제

🐛 Fix route

---

src/components/Header/index.jsx
src/pages/UserMyPage/UserInfo.jsx

원격상태 업데이트를 위한 pus test2

---

src/pages/SignUpPage/index.jsx

💄 Style : 백헤더 구분선 수정

---

src/components/Company/Modal/JobApplyModal.jsx
src/components/Company/Modal/JobApplyModal.scss
src/pages/RecruitmentInfo/JobDetail.jsx

채용공고상세페이지 지원하기 클릭시 모달생성
-채용공고 상세페이지 지원하기 클릭시 모달창 나오도록 설정
-모달창 이력서 수정하기 버튼 클릭시 이력서 수정페이지로 이동되게 라우터 경로 설정
-api 완성되는데로 연결할 예정

✨ AddJobApplyModal

---

src/pages/JobTraining/TrainingSearch.scss
src/pages/RecruitmentInfo/JobDetail.scss
src/pages/RecruitmentInfo/JobList.scss
src/pages/RecruitmentInfo/PublicJobList.scss
src/pages/RecruitmentInfo/RecruitmentInfo.scss
src/pages/RecruitmentInfo/SearchFilters.scss

채용정보 스타일 수정
-채용정보 전체적인 스타일,크기 오류 수정
기존 첫렌더링떄 크기가 작았다가 커지는 현상 수정,직업훈련정보 카드 크기 수정
- [ ✅ ] 기능이 정상 동작하나요?
- [ ✅ ] 팀 규칙에 맞게 커밋 메시지를 작성했나요?
-

🔧 Chore:recrutimentStyle

---

src/apis/RecruitmentApi.js
src/apis/companyPostingApi.js
src/pages/RecruitmentInfo/JobCard.jsx
src/pages/RecruitmentInfo/JobCard.scss
src/pages/RecruitmentInfo/JobDetail.jsx
src/pages/RecruitmentInfo/JobDetail.scss
src/pages/RecruitmentInfo/JobList.jsx
src/pages/RecruitmentInfo/JobList.scss
src/pages/RecruitmentInfo/PublicJobCard.jsx
src/pages/RecruitmentInfo/PublicJobCard.scss
src/pages/RecruitmentInfo/PublicJobList.jsx
src/pages/RecruitmentInfo/PublicJobList.scss
src/pages/RecruitmentInfo/RecruitmentInfo.scss
src/pages/RecruitmentInfo/SearchFilters.jsx
src/pages/RecruitmentInfo/SearchFilters.scss
src/pages/RecruitmentInfo/SearchResults.jsx
src/pages/RecruitmentInfo/SearchResults.scss
src/pages/RecruitmentInfo/index.jsx

채용정보 스타일 코드정리
-채용정보 페이지 스타일 팀규칙에 맞게 수정
- [ ✅ ] 기능이 정상 동작하나요?
- [ ✅ ] 팀 규칙에 맞게 커밋 메시지를 작성했나요?
-공공채용 목록 즐겨찾기 기능 삭제

🔧 Chore:RecruitmentStyle

---

src/apis/RecruitmentApi.js
src/apis/companyPostingApi.js
src/pages/RecruitmentInfo/JobCard.jsx
src/pages/RecruitmentInfo/JobCard.scss
src/pages/RecruitmentInfo/JobDetail.jsx
src/pages/RecruitmentInfo/JobDetail.scss
src/pages/RecruitmentInfo/JobList.jsx
src/pages/RecruitmentInfo/JobList.scss
src/pages/RecruitmentInfo/SearchResults.jsx
src/pages/RecruitmentInfo/index.jsx

일반채용정보 api 연결
-더미 데이터 삭제 posting api 연결
-채용상세페이지에 주소 복사하기 기능 추가
-payment_method 값에 따라 색깔 변경기능 추가
-검색필터 api 아직 미사용 검색기능x 추후 연결 예정

⚡️ Feat:jobList

---

src/pages/SignUpPage/CompanySignUpPage.scss
src/pages/SignUpPage/UserSignUpPage.scss

💄 Style : 약관동의 체크박스 css 수정

---

src/apis/authApi.js
src/components/Header/index.jsx

✨ Feat : 로그아웃 api 연결 및 모달 띄우기

---

src/pages/MainPage/MainJobCard.jsx
src/pages/MainPage/index.jsx
src/pages/RecruitmentInfo/JobList.jsx

메인페이지 인기공고 조회Api 연결
-메인페이지 인기공고 조회 api 연결
-

⚡️ Feat:PopularJobListApi

---

src/apis/favoriteApi.js
src/pages/MainPage/MainJobCard.jsx
src/pages/MainPage/index.jsx
src/pages/RecruitmentInfo/JobList.jsx

⚡️ Feat:favorite api

---

src/apis/favoriteApi.js
src/pages/RecruitmentInfo/JobDetail.jsx
src/pages/RecruitmentInfo/JobDetail.scss

-디테일페이지 코드 수정 
-근무조건 추가
-근무요일 '월,화,수,목,금' 일시 '평일' 로 표시  '토,일' 일시 '주말' 로 표시
-근무시간 오전 오후 표시
-

🔧Chore:jobdetailpage

---

src/App.jsx
src/apis/axios.dev.js
src/pages/MyResumes/EducationSection.jsx
src/pages/MyResumes/index.jsx
src/pages/UserMyPage/AgePopularity/index.jsx
src/pages/UserMyPage/InterestAnnouncement/index.jsx
src/pages/UserMyPage/JobRecommend/index.jsx
src/pages/UserMyPage/UserInfo/index.jsx
src/pages/UserMyPage/index.jsx
src/utils/testAxios.js

- 이력서 등록 api 구현 완료 / 추후 인스턴스로 변경 예정
- 마이페이지 유저 정보 부분 api 연결 완료 / 추후 인스턴스로 변경 예정
-

✨Feat: 이력서 등록 api 완 + 수정 추가 예정

---

src/apis/axios.prod.js
src/components/Header/index.jsx
src/utils/userLogin.js

🐛 Fix : 수정

---

src/apis/authApi.js
src/apis/axios.dev.js
src/apis/axios.prod.js
src/pages/SignUpPage/UserSignUpPage.jsx
src/utils/userLogin.js

🎨 Art : 함수명 변경

---

src/apis/RecruitmentApi.js
src/pages/RecruitmentInfo/JobDetail.jsx
src/pages/RecruitmentInfo/PublicJobList.jsx

-공공채용 api 페이지네이션 수정
-기존 10개만 받아온 공고 수정
-

🔧Chore:publicjob pagination

---

src/apis/axios.dev.js
src/apis/axios.prod.js

✨ Feat : 토큰 재발급

---

src/apis/axiosFormInstance.js

✨ Feat : 폼인스턴스에도 토큰 재발급

---

src/apis/authApi.js
src/pages/SignUpPage/UserSignUpPage.jsx

✨ Feat : 이메일 중복확인 api 연결

---

src/apis/authApi.js
src/pages/LoginPage/LoginPage.scss
src/pages/LoginPage/index.jsx
src/utils/userLogin.js

- 콘솔에 뜨는 경고메세지 수정 (폼태그 안에 넣어줌)
-

🐛 Fix : 오류 수정

---

src/App.jsx
src/apis/favoriteApi.js
src/components/Header/index.jsx
src/pages/MainPage/MainJobCard.jsx
src/pages/MainPage/MainPage.scss
src/pages/MainPage/index.jsx
src/pages/RecruitmentInfo/JobDetail.jsx

메인페이지 최근에 등록한 공고 api 연결(업데이트순)
-메인페이지 최근에 등록한 공고 api연결(업데이트순)
-채용공고 상세페이지 기업회원일시 지원하기,즐겨찾기 버튼 안보이게 수정
- [ ✅ ] 기능이 정상 동작하나요?
- [ ✅ ] 팀 규칙에 맞게 커밋 메시지를 작성했나요?
-

✨ Feat:mainJobApi

---

src/apis/authApi.js
src/apis/axiosPublicInstance.js

✨ Feat : 비로그인 인스턴스 생성

---

src/pages/MainPage/MainJobCard.jsx
src/pages/MainPage/MainPage.scss
src/pages/RecruitmentInfo/JobCard.jsx
src/pages/RecruitmentInfo/JobCard.scss
src/pages/RecruitmentInfo/JobDetail.jsx
src/pages/RecruitmentInfo/JobList.jsx

-북마크 아이콘 변경    FaStar>>>FaBookmark
-메인페이지,채용정보페이지,검색결과페이지.채용정보상세페이지 즐겨찾기 연결
-비로그인시 즐겨찾기 버튼 클릭시 로그인안내 모달 생성
-기업 유저 즐겨찾기 버튼 안보이게 수정

✨ Feat:bookMarkApi

---

src/pages/RecruitmentInfo/SearchFilters.jsx

검색필터 직종선택 리팩토링
-검색필터 직종선택 리팩토링
-

♻️ Refactor:searchFilters

---

src/App.jsx
src/apis/authApi.js
src/pages/LoginPage/KakaoCallbackPage.jsx
src/pages/LoginPage/index.jsx

✨ Feat : 카카오 로그인 API 연결

---

src/pages/RecruitmentInfo/JobDetail.jsx
src/pages/RecruitmentInfo/JobDetail.scss
src/pages/RecruitmentInfo/SalaryCalculator/CalculatorModal.jsx
src/pages/RecruitmentInfo/SalaryCalculator/CalculatorModal.scss
src/utils/checktime.js

-급여계산기 코드수정
-채용공고의 payment_method, salary, work_days, work_start_time, work_end_time 값을 가져와 시급,주급,월급,연봉 등으로
변환해서 계산 (세금3.3% or 4대보험 9.4% /주휴수당 클릭시 최종예정금액 출력)
-유틸폴더에 checktime.js <<<<(00:00부터 23:30까지 30분 단위로 시간 옵션을 자동 생성하는 배열)

🔧Chore:salary calculator

---

src/pages/MainPage/MainJobCard.jsx
src/pages/MainPage/index.jsx
src/pages/RecruitmentInfo/JobCard.jsx
src/pages/RecruitmentInfo/JobCard.scss
src/pages/RecruitmentInfo/JobDetail.jsx
src/pages/RecruitmentInfo/JobDetail.scss
src/pages/RecruitmentInfo/SearchFilters.jsx

잡카드 리펙토링
-jobCard 리펙토링
-즐겨찾기 수정
-상세페이지 리펙토링
-

♻️ Ref:jobCard

---

src/pages/MainPage/MainJobCard.jsx
src/pages/MainPage/index.jsx
src/pages/RecruitmentInfo/JobCard.jsx
src/pages/RecruitmentInfo/JobCard.scss
src/pages/RecruitmentInfo/JobDetail.jsx
src/pages/RecruitmentInfo/JobDetail.scss
src/pages/RecruitmentInfo/JobList.jsx
src/pages/RecruitmentInfo/JobList.scss
src/pages/RecruitmentInfo/PublicJobList.scss
src/pages/RecruitmentInfo/RecruitmentInfo.scss
src/pages/RecruitmentInfo/SearchFilters.jsx
src/pages/RecruitmentInfo/SearchResults.jsx

- joblist,jobcard 스타일 변경
- 상세페이지 새창으로 여는 버튼 추가
-

🎨Style:jobCard

---

src/pages/RecruitmentInfo/JobDetail.jsx
src/pages/RecruitmentInfo/SalaryCalculator/CalculatorModal.jsx
src/pages/RecruitmentInfo/SalaryCalculator/CalculatorModal.scss

-급여 계산기 스타일 수정
-공고 상세페이지 이력서 호출 조건 추가 (로그인)
-

🎨 Style:Calculator

---

src/components/Company/Modal/JobApplyModal.jsx
src/components/Company/Modal/LoginPromptModal.jsx
src/components/Company/styles/modal/JobApplyModal.scss
src/components/Company/styles/modal/LoginPromptModal.scss
src/pages/RecruitmentInfo/JobDetail.jsx
src/pages/RecruitmentInfo/JobDetail.scss
src/pages/RecruitmentInfo/SalaryCalculator/CalculatorModal.scss

.
-계산기,공고상세페이지 css수정 공고지원모달 css수정
-

💄 CalculatorModal/jobDetail

---

src/App.jsx
src/index.scss
src/pages/JobTraining/TrainingSearch.jsx
src/pages/JobTraining/TrainingSearch.scss
src/pages/RecruitmentInfo/JobCard.jsx
src/pages/RecruitmentInfo/JobCard.scss
src/pages/RecruitmentInfo/JobList.scss
src/pages/RecruitmentInfo/PublicJobCard.scss
src/pages/RecruitmentInfo/PublicJobList.scss
src/pages/RecruitmentInfo/RecruitmentInfo.scss
src/utils/variables.scss

채용 정보 / 직업훈련정보 css 수정

---

src/pages/UserMyPage/ApplyJobPosting/MyApplyJobCard.jsx
src/pages/UserMyPage/ApplyJobPosting/MyApplyJobList.jsx

이력서 지원 연속 취소 시 오류 해결

---

src/pages/RecruitmentInfo/SalaryCalculator/CalculatorModal.jsx
src/pages/RecruitmentInfo/SalaryCalculator/CalculatorModal.scss

.
-별거없음 그냥 계산기 윈도우로 열었는데 onclose 있느게 이상해서 삭제
-..

💄 Style:CalculatorModal

---

src/pages/RecruitmentInfo/SalaryCalculator/TaxInfo.jsx

🔧 Chore:Taxinfo

---

src/pages/RecruitmentInfo/JobDetail.jsx

🔧 Chore:Detailpage

---

src/components/Company/AnnouncementCard.jsx
src/components/Company/CategoryTitle.jsx
src/components/Company/CompanyCard.jsx
src/components/Company/Modal/Content.jsx
src/components/Company/Modal/DaumLocation.jsx
src/components/Company/Modal/Modal.jsx
src/components/Company/Modal/ModifiedText.jsx
src/components/Company/Modal/SimpleModal.jsx
src/components/Company/Modal/Title.jsx
src/components/Company/TimeDropDown.jsx

- 10분으로 설정되는 이슈 수정
- 자잘한 코드 정리 (console.log삭제, jsdoc정리 등)
-

♻️ Refactor: 자잘한 코드 리펙토링 (최종의 최종)

---

src/components/Company/Modal/Content.jsx
src/components/Company/Modal/InfoEditModal.jsx
src/components/Company/styles/modal/SimpleModal.scss
src/components/Company/styles/modal/modal.scss
src/index.scss
src/pages/CompanyInfoEdit/CompanyInfoEdit.scss
src/pages/JobTraining/TrainingSearch.scss
src/pages/MainPage/MainPage.scss
src/pages/RecruitmentInfo/PublicJobList.jsx
src/pages/RecruitmentInfo/PublicJobList.scss
src/pages/RecruitmentInfo/SearchFilters.scss
src/pages/UserMyPage/ApplyJobPosting/ApplyJobPosting.scss

- 화면 텍스트 등 불필요한 곳에 커서가 어색한 스타일 수정 (전체적으로 기본값)
- 통일성을 위해 호버,애니메이션 관련 누락된 곳 추가
-

자잘한 스타일 수정 (커서, 호버, 애니메이션)

---

src/components/Footer/index.jsx
src/pages/CompanyInfo/CompanyInfo.scss
src/pages/CompanyInfo/index.jsx

Style main

---

src/pages/JobTraining/TrainingSearch.jsx
src/pages/JobTraining/TrainingSearch.scss
src/pages/RecruitmentInfo/SearchFilters.jsx
src/pages/RecruitmentInfo/SearchFilters.scss

-Style : 채용 공고, 직업 훈련정보 옵션 화살표 위치 조정 및 화살표 추가

Style : 채용 공고, 직업 훈련정보 옵션 화살표 위치 조정 및 화살표 추가

---

src/pages/JobTraining/TrainingSearch.jsx

Chore : 직업 훈력 채용 공고 Params 주석 내용 복구

---

src/pages/SignUpPage/VerifyEmailPage.jsx

이메일 오류  페이지 확인

---

src/pages/LoginPage/index.jsx

네이버 로그인 오류

---

.github/workflows/deploy-prod.yml
src/pages/LoginPage/index.jsx

Fix:CICD ENV 오류 수정

---

src/pages/SignUpPage/CompanySignUpPage.jsx
src/pages/SignUpPage/UserSignUpPage.jsx

- 약관동의 체크 후 자세히보기 버튼 눌렀을때 회원가입 완료 되는 오류 수정
-

🐛 Fix : 회원가입 약관동의 자세히보기 버튼 오류 수정

---

.github/workflows/deploy-prod.yml
src/pages/LoginPage/index.jsx

- develop > merge

---

src/pages/SignUpPage/CompanySignUpPage.jsx
src/utils/validation.js

- 유효성 검사 없이 다음으로 넘어가지는 오류 수정
-

🐛 Fix : 기업회원가입시 비밀번호 유효성 오류 수정

---

src/components/Company/inputs/JobRequirement.jsx
src/components/Company/styles/inputs/JobRequirement.scss

체크박스 위치 조정

---

src/apis/companyPostingApi.js
src/components/Company/DayDropDown.jsx
src/components/Company/InputDropDown.jsx
src/components/Company/Modal/DaumLocation.jsx
src/components/Company/Modal/Modal.jsx
src/components/Company/TimeDropDown.jsx
src/components/Company/styles/InputDropDown.scss
src/pages/Announcement/index.jsx
src/pages/CompanyMyPage/index.jsx
src/pages/CompanyResumes/index.jsx
src/pages/RecruitmentInfo/JobDetail.jsx

-공고 등록/수정 시 모집기간, 근무시간 드롭다운 제대로 작동하지 않는 이슈 수정
-누락 props 타입 선언 추가
-남은 console.log 삭제
-

모집기간, 시간 설정 이슈 수정

---

src/index.scss

🔧chore : main PR 을 위한 commit
